In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import h5py
# import skimage
import matplotlib.pyplot as plt
import sys
# Input data files are avahilable in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory


In [2]:
# Any results you write to the current directory are saved as output.

#File Format
#f=h5py.File('../input/food_c101_n1000_r384x384x3.h5','r')
f=h5py.File('../raw_data/dataset_food/food_c101_n10099_r64x64x3.h5','r')
print(list(f.keys()))
print(len(f["category"]))
print(len(f["category_names"]))
print(len(f["images"]))

['category', 'category_names', 'images']
10099
101
10099


In [3]:
f['category']

<HDF5 dataset "category": shape (10099, 101), type "|b1">

In [4]:
f['images'].shape, f['category'].shape, f['category_names'].shape

((10099, 64, 64, 3), (10099, 101), (101,))

In [5]:
f['images'][3].shape, f['category'][3], f['category_names'][3]

((64, 64, 3),
 array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False]),
 b'beef_carpaccio')

In [6]:
a = f['category'][3].astype(int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.where(a == 1)[0][0]

60

In [8]:
f['category_names'][np.where(a == 1)[0][0]]

b'lobster_bisque'

In [9]:
# Print Sample Pictures
# print([int(i) for i in f["category"][0]])
# print(f["images"][0].shape)
# fig=plt.figure(figsize=(20,20))
# n=25
# col=5
# for i in range(n):
#     ax=fig.add_subplot(n/col,col,i+1)
#     #ax.set_title(f["category_names"][i].decode())
#     ax.imshow(f["images"][i])

In [10]:
f['category'][:]

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [11]:
f['category_names'][:]

array([b'apple_pie', b'baby_back_ribs', b'baklava', b'beef_carpaccio',
       b'beef_tartare', b'beet_salad', b'beignets', b'bibimbap',
       b'bread_pudding', b'breakfast_burrito', b'bruschetta',
       b'caesar_salad', b'cannoli', b'caprese_salad', b'carrot_cake',
       b'ceviche', b'cheese_plate', b'cheesecake', b'chicken_curry',
       b'chicken_quesadilla', b'chicken_wings', b'chocolate_cake',
       b'chocolate_mousse', b'churros', b'clam_chowder', b'club_sandwich',
       b'crab_cakes', b'creme_brulee', b'croque_madame', b'cup_cakes',
       b'deviled_eggs', b'donuts', b'dumplings', b'edamame',
       b'eggs_benedict', b'escargots', b'falafel', b'filet_mignon',
       b'fish_and_chips', b'foie_gras', b'french_fries',
       b'french_onion_soup', b'french_toast', b'fried_calamari',
       b'fried_rice', b'frozen_yogurt', b'garlic_bread', b'gnocchi',
       b'greek_salad', b'grilled_cheese_sandwich', b'grilled_salmon',
       b'guacamole', b'gyoza', b'hamburger', b'hot_and_sour_

In [12]:
target = f['category'][:].astype(int)
np.where(target[0] == 1)[0][0]

33

In [13]:
names = f['category_names'][:]
names

array([b'apple_pie', b'baby_back_ribs', b'baklava', b'beef_carpaccio',
       b'beef_tartare', b'beet_salad', b'beignets', b'bibimbap',
       b'bread_pudding', b'breakfast_burrito', b'bruschetta',
       b'caesar_salad', b'cannoli', b'caprese_salad', b'carrot_cake',
       b'ceviche', b'cheese_plate', b'cheesecake', b'chicken_curry',
       b'chicken_quesadilla', b'chicken_wings', b'chocolate_cake',
       b'chocolate_mousse', b'churros', b'clam_chowder', b'club_sandwich',
       b'crab_cakes', b'creme_brulee', b'croque_madame', b'cup_cakes',
       b'deviled_eggs', b'donuts', b'dumplings', b'edamame',
       b'eggs_benedict', b'escargots', b'falafel', b'filet_mignon',
       b'fish_and_chips', b'foie_gras', b'french_fries',
       b'french_onion_soup', b'french_toast', b'fried_calamari',
       b'fried_rice', b'frozen_yogurt', b'garlic_bread', b'gnocchi',
       b'greek_salad', b'grilled_cheese_sandwich', b'grilled_salmon',
       b'guacamole', b'gyoza', b'hamburger', b'hot_and_sour_

In [14]:
names[np.where(target[0] == 1)[0][0]]

b'edamame'

In [15]:
target.shape

(10099, 101)

In [16]:
names[np.where(target[0] == 1)][0]

b'edamame'

In [17]:
target[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
sorted_df = pd.DataFrame(target, columns=[names]).sum()

In [19]:
cats = pd.DataFrame(sorted_df, columns=['Count'])

In [20]:
cats.sort_values(by='Count')

Count
b'scallops'            73
b'french_toast'        77
b'poutine'             84
b'crab_cakes'          85
b'tacos'               85
...                   ...
b'omelette'           117
b'ice_cream'          117
b'croque_madame'      117
b'red_velvet_cake'    117
b'caprese_salad'      118

[101 rows x 1 columns]

In [59]:
cats.sort_values(by='Count').describe()

Count
count  101.000000
mean    99.990099
std      8.527010
min     73.000000
25%     95.000000
50%    100.000000
75%    105.000000
max    118.000000

In [23]:
images = f['images'][:]

In [26]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator